spring:
  application:
    name: media
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enable: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/astfx_media_db?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${DB_USER:root}
    password: ${DB_PWD:1305}

server:
  port: 8763

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 40000

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173}