spring:
  application:
    name: media
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enable: false
  datasource:
    url: jdbc:mysql://192.168.1.150:3306/PROTO_MEDIA?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: dba-root
    password: nUKXQ3C35F2Kcq4_
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

server:
  port: 8763

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
